config.localContrastConfig.doLocalContrast = False
config.imageRemappingConfig.absMax = 11000
config.luminanceConfig.stretch = 600
config.luminanceConfig.Q = 0.7
config.luminanceConfig.max = 100
config.luminanceConfig.highlight = 0.91
config.luminanceConfig.shadow = 0.12
config.luminanceConfig.midtone = 0.25
config.doPSFDeconcovlve = False
config.exposureBrackets = None
config.recenterNoise = 0.3
config.colorConfig.maxChroma = 80
config.colorConfig.saturation = 0.6
config.cieWhitePoint = (0.28, 0.28)
config.gamutMethod = "mapping"
config.channelConfig = {}
config.luminanceConfig.shadow = 0.0
config.luminanceConfig.midtone = 0.2
